version: "3"

services:
  pi-academy-api:
    build: ./
    volumes:
      - ./:/code
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: pi_academy
      DB_USER: admin
      DB_PASS: admin
    ports:
      - 80:8080

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8081:80

volumes:
  postgresdata: {}
