"""Create event table

Revision ID: 16f14bde1e36
Revises: 58dd29a7931e
Create Date: 2020-09-29 12:22:35.005158

"""
from alembic import op
import sqlalchemy as sa
import fastapi_utils


# revision identifiers, used by Alembic.
revision = '16f14bde1e36'
down_revision = '58dd29a7931e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('guid', fastapi_utils.guid_type.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('schedule', sa.DateTime(), nullable=True),
    sa.Column('enrollment_guid', fastapi_utils.guid_type.GUID(), nullable=True),
    sa.Column('user_guid', fastapi_utils.guid_type.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_guid'], ['enrollments.guid'], ),
    sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_events_guid'), 'events', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_guid'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
