"""Create enrollments table

Revision ID: 3f47755f2312
Revises: b98c6adad1bc
Create Date: 2020-09-28 20:53:25.007845

"""
from alembic import op
import sqlalchemy as sa
import fastapi_utils


# revision identifiers, used by Alembic.
revision = '3f47755f2312'
down_revision = 'b98c6adad1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('guid', fastapi_utils.guid_type.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('course_guid', fastapi_utils.guid_type.GUID(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_guid'], ['courses.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_enrollments_guid'), 'enrollments', ['guid'], unique=False)
    op.create_table('enrollment_to_user_associations',
    sa.Column('user_guid', fastapi_utils.guid_type.GUID(), nullable=True),
    sa.Column('enrollment_guid', fastapi_utils.guid_type.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_guid'], ['enrollments.guid'], ),
    sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment_to_user_associations')
    op.drop_index(op.f('ix_enrollments_guid'), table_name='enrollments')
    op.drop_table('enrollments')
    # ### end Alembic commands ###
