"""Index guid field

Revision ID: 5cd97979b401
Revises: 8ef627b7db6d
Create Date: 2020-09-26 17:43:22.884726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd97979b401'
down_revision = '8ef627b7db6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_courses_guid'), 'courses', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_guid'), table_name='courses')
    # ### end Alembic commands ###
