"""Create profile table

Revision ID: a79d85ab0982
Revises: 16f14bde1e36
Create Date: 2020-09-29 12:41:56.834451

"""
from alembic import op
import sqlalchemy as sa
import fastapi_utils


# revision identifiers, used by Alembic.
revision = 'a79d85ab0982'
down_revision = '16f14bde1e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('guid', fastapi_utils.guid_type.GUID(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('interests', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['guid'], ['users.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
