"""Cascade child on parent delete

Revision ID: b19431af8cb2
Revises: a79d85ab0982
Create Date: 2020-10-09 17:46:13.996873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19431af8cb2'
down_revision = 'a79d85ab0982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discussions_author_guid_fkey', 'discussions', type_='foreignkey')
    op.drop_constraint('discussions_enrollment_guid_fkey', 'discussions', type_='foreignkey')
    op.create_foreign_key(None, 'discussions', 'users', ['author_guid'], ['guid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'discussions', 'enrollments', ['enrollment_guid'], ['guid'], ondelete='SET NULL')
    op.drop_constraint('enrollment_to_user_associations_user_guid_fkey', 'enrollment_to_user_associations', type_='foreignkey')
    op.drop_constraint('enrollment_to_user_associations_enrollment_guid_fkey', 'enrollment_to_user_associations', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment_to_user_associations', 'users', ['user_guid'], ['guid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'enrollment_to_user_associations', 'enrollments', ['enrollment_guid'], ['guid'], ondelete='CASCADE')
    op.drop_constraint('enrollments_course_guid_fkey', 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'courses', ['course_guid'], ['guid'], ondelete='CASCADE')
    op.drop_constraint('events_enrollment_guid_fkey', 'events', type_='foreignkey')
    op.drop_constraint('events_user_guid_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'enrollments', ['enrollment_guid'], ['guid'], ondelete='SET NULL')
    op.create_foreign_key(None, 'events', 'users', ['user_guid'], ['guid'], ondelete='SET NULL')
    op.drop_constraint('user_profiles_guid_fkey', 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['guid'], ['guid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key('user_profiles_guid_fkey', 'user_profiles', 'users', ['guid'], ['guid'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_user_guid_fkey', 'events', 'users', ['user_guid'], ['guid'])
    op.create_foreign_key('events_enrollment_guid_fkey', 'events', 'enrollments', ['enrollment_guid'], ['guid'])
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key('enrollments_course_guid_fkey', 'enrollments', 'courses', ['course_guid'], ['guid'])
    op.drop_constraint(None, 'enrollment_to_user_associations', type_='foreignkey')
    op.drop_constraint(None, 'enrollment_to_user_associations', type_='foreignkey')
    op.create_foreign_key('enrollment_to_user_associations_enrollment_guid_fkey', 'enrollment_to_user_associations', 'enrollments', ['enrollment_guid'], ['guid'])
    op.create_foreign_key('enrollment_to_user_associations_user_guid_fkey', 'enrollment_to_user_associations', 'users', ['user_guid'], ['guid'])
    op.drop_constraint(None, 'discussions', type_='foreignkey')
    op.drop_constraint(None, 'discussions', type_='foreignkey')
    op.create_foreign_key('discussions_enrollment_guid_fkey', 'discussions', 'enrollments', ['enrollment_guid'], ['guid'])
    op.create_foreign_key('discussions_author_guid_fkey', 'discussions', 'users', ['author_guid'], ['guid'])
    # ### end Alembic commands ###
